<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Svg\\' => array($vendorDir . '/phenx/php-svg-lib/src/Svg'),
    'Sabberworm\\CSS\\' => array($vendorDir . '/sabberworm/php-css-parser/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'FontLib\\' => array($vendorDir . '/phenx/php-font-lib/src/FontLib'),
    'Faker\\' => array($vendorDir . '/fakerphp/faker/src/Faker'),
    'Dompdf\\' => array($vendorDir . '/dompdf/dompdf/src'),
);
